# Generated by Django 6.1.1 on 2026-09-22 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('cantidad_inicial', models.PositiveIntegerField(help_text='Cantidad de gallinas al iniciar el lote')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMortalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('causa', models.CharField(choices=[('enfermedad', 'Enfermedad'), ('calor', 'Estrés calórico'), ('depredador', 'Depredador'), ('accidente', 'Accidente'), ('desconocida', 'Causa desconocida'), ('otra', 'Otra')], default='desconocida', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortalidades', to='accounts.lote')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
