# Generated by Django 6.1.1 on 2026-09-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('huevos_recolectados', models.IntegerField()),
                ('cubetas_armadas', models.IntegerField()),
            ],
        ),
    ]
