# Generated by Django 6.1.1 on 2026-09-27 21:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galpon_Proyecto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('cantidad_inicial', models.PositiveIntegerField(help_text='Cantidad de gallinas al iniciar el lote')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('poblacion_gallinas', models.PositiveIntegerField(default=1000)),
                ('bultos_consumidos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kilos_por_bulto', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('stock_disponible', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
            ],
        ),
        migrations.AlterModelOptions(
            name='registroproduccion',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='registroproduccion',
            name='cubetas_armadas',
        ),
        migrations.RemoveField(
            model_name='registroproduccion',
            name='huevos_recolectados',
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='cantidad_cubetas',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='cantidad_huevos',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registroproduccion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='RegistroMortalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('causa', models.CharField(choices=[('enfermedad', 'Enfermedad'), ('calor', 'Estrés calórico'), ('depredador', 'Depredador'), ('accidente', 'Accidente'), ('desconocida', 'Causa desconocida'), ('otra', 'Otra')], default='desconocida', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortalidades', to='Galpon_Proyecto.lote')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
