# Generated by Django 6.1.1 on 2026-09-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galpon_Proyecto', '0004_fix_venta_cantidad_huevos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cantidad_huevos',
            field=models.PositiveIntegerField(),
        ),
    ]
