# Generated by Django 6.1.1 on 2026-09-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galpon_Proyecto', '0005_alter_venta_cantidad_huevos'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroproduccion',
            name='cantidad_huevos_rotos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
