# Generated by Django 6.1.1 on 2026-09-28 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galpon_Proyecto', '0006_registroproduccion_cantidad_huevos_rotos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('iniciador', 'Iniciador'), ('engorde', 'Engorde'), ('finalizador', 'Finalizador'), ('medicado', 'Medicado')], max_length=20)),
                ('cantidad_bultos', models.PositiveIntegerField()),
                ('kilos_por_bulto', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('proveedor', models.CharField(max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
