# Generated by Django 6.1.1 on 2026-09-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Galpon_Proyecto', '0007_alimento'),
        ('Galpon_Proyecto', '0007_inventario_alertastock'),
    ]

    operations = [
    ]
