# Generated by Django 6.1.1 on 2026-10-06 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galpon_Proyecto', '0008_merge_0007_alimento_0007_inventario_alertastock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('servicios', 'Servicios públicos'), ('transporte', 'Transporte'), ('empaque', 'Empaque'), ('mano_obra', 'Mano de obra'), ('insumos', 'Insumos'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(help_text='Detalle del gasto', max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto operativo',
                'verbose_name_plural': 'Gastos operativos',
                'ordering': ['-fecha'],
            },
        ),
    ]
